version: "2"
services:
  node:
    image: "wsdl:1.0"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
      - TZ=America/Mexico_City
    volumes:
      - ./:/home/node/app
    expose:
      - "3000"
    ports: # use if it is necessary to expose the container to the host machine
      - "3000:3000"
    command: "npm start"